// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJfxYFPwEIMj1YkP2Qqp3nr19bsLklmac',
    appId: '1:904187917197:web:bc7e427e8afc629e8743c4',
    messagingSenderId: '904187917197',
    projectId: 'weekflow-ac880',
    authDomain: 'weekflow-ac880.firebaseapp.com',
    storageBucket: 'weekflow-ac880.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhrZEciyn5kCJnFAHbIPYFPloYL5ax414',
    appId: '1:904187917197:android:791481a348a47f6a8743c4',
    messagingSenderId: '904187917197',
    projectId: 'weekflow-ac880',
    storageBucket: 'weekflow-ac880.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBszSlCLr__-sqatP9m1YX8fjlGzfiILkc',
    appId: '1:904187917197:ios:0a002acca168c38e8743c4',
    messagingSenderId: '904187917197',
    projectId: 'weekflow-ac880',
    storageBucket: 'weekflow-ac880.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBszSlCLr__-sqatP9m1YX8fjlGzfiILkc',
    appId: '1:904187917197:ios:0a002acca168c38e8743c4',
    messagingSenderId: '904187917197',
    projectId: 'weekflow-ac880',
    storageBucket: 'weekflow-ac880.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJfxYFPwEIMj1YkP2Qqp3nr19bsLklmac',
    appId: '1:904187917197:web:def13e6964925f8d8743c4',
    messagingSenderId: '904187917197',
    projectId: 'weekflow-ac880',
    authDomain: 'weekflow-ac880.firebaseapp.com',
    storageBucket: 'weekflow-ac880.firebasestorage.app',
  );
}
